using AutoMapper.Execution;
using Azure;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using NLog.Layouts;
using Polly;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.IO;
using System.Net.NetworkInformation;
using System.Numerics;
using System.Reflection;
using System.Security.Claims;
using System;
using Viper.Classes.SQLContext;
using Viper.Models.AAUD;
using Viper.Models.CTS;
using Viper.Models.EquipmentLoan;
using Viper.Models.VIPER;
using System.Data;

namespace Viper.Areas.Directory.Models
{
    public class UserInfoResult
    {
        public string? Email {get; set; } = null;
        public string? DisplayFullName {get; set; } = null;
        public string? Title {get; set; } = null;
        public string? Department {get; set; } = null;
        public string? EmailHost {get; set; } = null;
        public string? LoginId {get; set; } = null;
        public string? URI {get; set; } = null;
        public string? Phone {get; set; } = null;
        public string? Mobile {get; set; } = null;
        public string? Pager {get; set; } = null;
        public string? PostalAddress {get; set; } = null;
        public string? MothraId {get; set; } = null;
        public string? EmployeeId {get; set; } = null;
        public string? StudentId {get; set; } = null;
        public string? IamId {get; set; } = null;
        public string? Pidm {get; set; } = null;
        public string? MivId {get; set; } = null;
        public string? EmployeePrimaryTitle {get; set; } = null;
        public string? EmployeeSchoolDivision {get; set; } = null;
        public string? EmployeeStatus {get; set; } = null;
        public string? EmployeeTerm {get; set; } = null;
        public string? EmployeeHomeDepartment {get; set; } = null;
        public string? EmployeeEffortHomeDepartment {get; set; } = null;
        public string? EmployeeTeachingHomeDepartment {get; set; } = null;
        public string? EmployeeTeachingPercentFulltime {get; set; } = null;
        public string? StudentPriorName {get; set; } = null;
        public string? StudentBannerId {get; set; } = null;
        public bool StudentConfidential {get; set; } = false;
        public string? StudentStatus {get; set; } = null;
        public string? StudentPrimaryMajor {get; set; } = null;
        public string? StudentAllMajors {get; set; } = null;
        public string? StudentRegistrationStatus {get; set; } = null;
        public string? StudentClassLevel {get; set; } = null;
        public string? StudentClassOf {get; set; } = null;
        public string? PPSId {get; set; } = null;
        public string? OFullName {get; set; } = null;
        public bool IsEmployee {get; set; } = false;
        public bool IsHSEmployee {get; set; } = false;
        public bool IsFaculty {get; set; } = false;
        public bool IsStudent {get; set; } = false;
        public bool IsStaff {get; set; } = false;
        public bool IsExternal {get; set; } = false;
        public string? AssociationsTitle {get; set; } = null;
        public string? AssociationsTitleCode {get; set; } = null;
        public string? AssociationsDepartment {get; set; } = null;
        public string? AssociationsDepartmentCode {get; set; } = null;
        public string? AssociationsAdminDepartment {get; set; } = null;
        public string? AssociationsAdminDepartmentAbbrev { get; set; } = null;
        public string? AssociationsAdminDepartmentCode {get; set; } = null;
        public string? AssociationsAppointmentDepartment {get; set; } = null;
        public string? AssociationsAppointmentDepartmentAbbrev { get; set; } = null;
        public string? AssociationsAppointmentDepartmentCode {get; set; } = null;
        public string? AssociationsPositionType {get; set; } = null;
        public string? AssociationsEmployeeClass {get; set; } = null;
        public string? AssociationsPercentFulltime {get; set; } = null;
        public string? AssociationsStart {get; set; } = null;
        public string? AssociationsEnd {get; set; } = null;
        public string? UCPathJobCode {get; set; } = null;
        public string? UCPathJobDescription {get; set; } = null;
        public string? UCPathDepartmentId {get; set; } = null;
        public string? UCPathDepartmentDescription {get; set; } = null;
        public string? UCPathJobStatus {get; set; } = null;
        public string? UCPathEmployeeStatus {get; set; } = null;
        public string? UCPathJobStatusDescription {get; set; } = null;
        public string? UCPathPositionEffective {get; set; } = null;
        public string? UCPathEndDate {get; set; } = null;
        public string? UCPathFTE {get; set; } = null;
        public string? UCPathUnion {get; set; } = null;
        public string? UCPathReportsToName {get; set; } = null;
        public string? UCPathReportsToPosition {get; set; } = null;
        public List<UCPathResult>? UCPathHistory = new List<UCPathResult>();
        public List<IDCardResult>? IDCards = new List<IDCardResult>();
        public List<KeyResult>? Keys = new List<KeyResult>();
        public List<LoanResult>? Loans = new List<LoanResult>();
        public string? InstinctID {get; set; } = null;
        public string? InstinctUsername {get; set; } = null;
        public string? InstinctRoles {get; set; } = null;
        public string? InstinctStatus {get; set; } = null;
        public string? InstinctPasswordExpiresAt {get; set; } = null;
        public bool? InstinctIsActive {get; set; } = null;
    }
}