/**
 * RAPS permissions for the Career Selection app. Mirrors CareerSelectionPermissions.cs.
 */

const CAREER_SELECTION_PERMISSION_PREFIX = "SVMSecure.CareerSelection"

const CAREER_SELECTION_PERMISSIONS = {
    ADMIN: `${CAREER_SELECTION_PERMISSION_PREFIX}.Admin`,
    READ_ONLY: `${CAREER_SELECTION_PERMISSION_PREFIX}.ReadOnly`,
    STUDENT: `${CAREER_SELECTION_PERMISSION_PREFIX}.Student`,
    FACULTY: `${CAREER_SELECTION_PERMISSION_PREFIX}.Faculty`,
    VIEW_OWN: `${CAREER_SELECTION_PERMISSION_PREFIX}.ViewOwn`,
} as const

export { CAREER_SELECTION_PERMISSION_PREFIX, CAREER_SELECTION_PERMISSIONS }
